---

# task file for dgnest.apache

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install apache package dependencies
  sudo: yes
  apt:

    name: "{{ item }}"

    state: present
  register: install_apache_package_dependencies
  when: _apache_package_dependencies is defined
  with_items: _apache_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_apache_package_dependencies.stdout_lines

- name: Install apache dependencies
  sudo: yes
  apt:

    name: "{{ item.name }}"

    state: present
  register: install_apache_dependencies
  when: _apache_dependencies is defined
  with_items: _apache_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_apache_dependencies.stdout_lines