---
# task for dgnest.apache

- name: Install packages via pip apache
  sudo: yes

  pip: name="{{ item.name }}" version="{{ item.version }}"

  when: apache_pip_dependencies is defined
  with_items: apache_pip_dependencies
