---
# task for hadenlabs.apache

- name: a2ensite "{{ apache_domain }}"
  command: a2ensite "{{ apache_domain }}".vhost.conf
  notify:
  - restart apache2

- name: enabled modules
  apache2_module: name="{{item}}" state=present
  with_items: apache_modules
  when: apache_modules is defined
  notify:
  - restart apache2